FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN echo "VITE_API_URL=http://161.116.82.76:8080" > .env
RUN echo "NODE_ENV=development" >> .env

EXPOSE 5000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5000"]