import React from 'react';
import './Citation.css';
import { FaQuoteLeft, FaExternalLinkAlt } from 'react-icons/fa';
import team1 from '../assets/logo.png';
import team2 from '../assets/logo.png';
import team3 from '../assets/logo.png'; 

const Citation = () => {
  return (
    <div className="citation">
      <h1>Citation Guidelines</h1>

      {/* Citation Box */}
      <section className="citation-box">
        <FaQuoteLeft className="quote-icon" />
        <p>
          If you use the paleocoordinates generated by this website in your research, please cite us using the following reference:
        </p>
        <div className="citation-ref">
          Scholz Murcia, N., Monleón-Getino, A., & Rodríguez, A. (2025). Paleocoordinates Calculator: An online tool to reconstruct ancient geographic positions using Global Plate Models. University of Barcelona.
        </div>
        <p>
          For plate models and methodology, please cite:
        </p>
        <div className="citation-ref small">
          Jones, L. A., Gearty, W., Allen, B. J., Eichenseer, K., Dean, C. D., Galván, S., Chiarenza, A. A. (2023). Palaeoverse: A community-driven R package to support palaeobiological analysis. <em>Methods in Ecology and Evolution, 14(9), 2189–2510.</em> 
          <a href="https://doi.org/10.1111/2041-210X.14099" target="_blank" rel="noopener noreferrer">
            DOI link <FaExternalLinkAlt className="inline-icon" />
          </a>
        </div>
      </section>

      {/* Team Section */}
      <section className="team-section">
        <h2>Meet the Team</h2>
        <div className="team-grid">
          <div className="team-member">
            <img src={team1} alt="Noa Scholz Murcia" />
            <h3>Noa Scholz Murcia</h3>
            <p className="role">Project Lead & R Developer</p>
            <p>
              PhD student in Statistics at the University of Barcelona. Noa led the development of the paleocoordinate system and integrated the palaeoverse methodology with the web tool.
            </p>
          </div>

          <div className="team-member">
            <img src={team2} alt="Alex Collaborator" />
            <h3>Alex Collaborator</h3>
            <p className="role">Web Developer & Data Engineer</p>
            <p>
              Responsible for building the React-based frontend, processing user-uploaded files, and managing the interactive map and download functionality.
            </p>
          </div>

          <div className="team-member">
            <img src={team3} alt="Antonio Monleón Getino" />
            <h3>Antonio Monleón Getino</h3>
            <p className="role">Statistical Advisor & Scientific Contributor</p>
            <p>
              Professor of Statistics at the University of Barcelona. Antonio contributed to the scientific foundation of the methodology and supported the statistical validation of the paleocoordinate calculations.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Citation;


